### ISSUE TITLE
博主，想请问你一个问题

### ISSUE THREAD

**Issue by imurluck** [liying2008/neu-ipgw#2]
mRequest.setUserAgent("Mozilla/5.0 (Linux; Android 4.4.4; Nexus 5 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.114 Mobile Safari/537.36");
        mRequest.setAcceptLanguage("zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4");
        mRequest.add("action", "login")
                .add("ac_id", 1)
                .add("user_ip", "")
                .add("nas_ip", "")
                .add("user_mac", "")
                .add("username", uid)
                .add("password", password);

 mRequest.setUserAgent("Mozilla/5.0 (Linux; Android 4.4.4; Nexus 5 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.114 Mobile Safari/537.36");
        mRequest.setAcceptLanguage("zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4");
        mRequest.add("action", "auto_logout")
                .add("info", "")
                .add("nas_ip", "")
                .add("user_ip", ip);

这些请求体中的内容博主是在哪里找到的呢？看到了请回复一下，万分感谢

**Comment by liying2008** [comment]
浏览器抓包或使用其他工具（如Fiddler 4）抓包。具体方法可以网上搜索。

**Comment by imurluck** [comment]
嗯  谢谢师兄
